# permissions for end users to edit visitorves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: visitorfe-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: visitorapp
    app.kubernetes.io/part-of: visitorapp
    app.kubernetes.io/managed-by: kustomize
  name: visitorfe-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - visitorves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - visitorves/status
  verbs:
  - get
