# permissions for end users to view visitorbes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: visitorbe-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: visitorapp
    app.kubernetes.io/part-of: visitorapp
    app.kubernetes.io/managed-by: kustomize
  name: visitorbe-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - visitorbes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - visitorbes/status
  verbs:
  - get
